quarkus.http.port=9002
quarkus.http.host=0.0.0.0

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.rest-client.awesome-api.url=https://economia.awesomeapi.com.br
quarkus.rest-client.binance-exchange.url=https://api.binance.com
quarkus.rest-client.bitget-exchange.url=https://api.bitget.com
quarkus.rest-client.bitpreco-exchange.url=https://api.bitpreco.com
quarkus.rest-client.bybit-exchange.url=https://api.bybit.com
quarkus.rest-client.kucoin-exchange.url=https://api.kucoin.com
quarkus.rest-client.mexc-exchange.url=https://api.mexc.com
quarkus.rest-client.okx-exchange.url=https://www.okx.com

# System properties para Proxy HTTP/HTTPS
# Configurado via linha de comando: -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8888

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=API de Cambio
quarkus.smallrye-openapi.info-version=1.0.0
